version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn build-bundle
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn test:unit --runInBand
      - run: yarn codecov
  lint:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn lint

  doc-build:
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd doc-build
            gem update --system
            gem install bundler
      - run:
          name: Bundle Install
          command: |
            cd doc-build
            bundle check || bundle install
      - run:
          name: Jekyll build
          command: |
            cd doc-build
            bundle exec jekyll build
      - persist_to_workspace:
          root: ./doc-build
          paths:
            - _site
  doc-deploy:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - attach_workspace:
          at: ./doc-build/
      - add_ssh_keys:
          fingerprints:
            - "db:49:cb:f3:4b:23:9e:b3:17:b5:ce:95:82:12:b4:24"
      - run:
          name: Install and configure dependencies
          command: |
            npm install --silent gh-pages@2.0.1
            git config user.email "dev+vqb@toucantoco.com"
            git config user.name "ToucanToco Dev Team"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            cd doc-build/_site
            ../../node_modules/.bin/gh-pages --dist .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - lint
  Doc_build_deploy:
    jobs:
      - doc-build:
          filters:
            branches:
              only:
                - master
                - f/publish-doc
      - doc-deploy:
          requires:
            - doc-build
          filters:
            branches:
              only:
                - master
                - f/publish-doc
