version: 2

jobs:
  build:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run: yarn
      - run: yarn build-bundle
  test:
    docker:
      # use node11.10 image instead of node11.11 until
      # https://github.com/facebook/jest/issues/8069 is fixed
      - image: circleci/node:11.10
    steps:
      - checkout
      - run: yarn
      - run: yarn test:unit --runInBand
      - run: yarn codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
