version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn build-bundle
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn test:unit --runInBand
      - run: yarn codecov
  lint:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn lint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - lint
