version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn build-bundle
  test:
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - run: yarn
      - run: yarn lint:ci
      - run: yarn test:unit --runInBand
      - run: yarn codecov
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          context: SonarCloud
