name: Playground docker image

on:
  # Trigger analysis when pushing pull requests
  pull_request:
    types: [opened, synchronize, reopened]
    path-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    path-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-${{ github.head_ref }}
          ${{ runner.os }}-buildx-

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: toucantoco
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # `/` char is not authorized in docker images tags
    - name: Sanitize branch name
      id: sanitize_branch_name
      run: echo "::set-output name=value::$(echo ${{ github.head_ref }} | tr '/' '-')"

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: toucantoco/weaverbird-playground:${{ steps.sanitize_branch_name.outputs.value }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci) -a playground -p docker.io/toucantoco/weaverbird-playground:${{ steps.sanitize_branch_name.outputs.value }}
      env:
        CI: true
        # The image is public, so any user can retrieve it (like our service account toucantokar)
        DOCKER_USERNAME: toucantokar
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOUCANTOKAR_PASSWORD }}
