name: Playground docker image

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request, only if `server/` files are modified
  push:
    branches:
      - master
    path-ignore:
      - 'docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    path-ignore:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: false
        tags: toucantoco/weaverbird-playground:${GITHUB_REF##*/}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
