# From https://docs.featurepeek.com/github-actions/
name: Build playground
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Build Weaverbird module
      run: yarn build-bundle
    - name: Copy weaverbird script into dist folder
      run: cp --remove-destination dist/weaverbird.browser.js playground/dist/weaverbird.browser.js
    - name: Copy weaverbird CSS into dist folder
      run: cp --remove-destination dist/weaverbird.css playground/dist/playground.css
    - name: Copy playground script into dist folder
      run: cp --remove-destination playground/app.js playground/dist/app.js
    - name: Ping FeaturePeek
      run: bash <(curl -s https://peek.run/ci) -a playground
      env:
        CI: true
